[package]
name = "mcts"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
rand = "0.8.4"
wasm-bindgen = "0.2.37"
console_error_panic_hook="0.1.6"


# [dependencies]
