services:
  wasm-builder:
    build: .
    volumes:
      # direct build output into pkg directory
      # unfortunately this is owned by root if you're running docker-compose as root 
       # haven't solved this yet, requires a chown after build
      - ./docs/pkg:/app/pkg

    
