/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function greet(a: number, b: number): void;
export function __wbg_connect4game_free(a: number): void;
export function connect4game_new(): number;
export function connect4game_reset(a: number): void;
export function connect4game_cell(a: number, b: number, c: number, d: number): void;
export function connect4game_player(a: number, b: number): void;
export function connect4game_result(a: number, b: number): void;
export function connect4game_suggest_move(a: number, b: number): number;
export function connect4game_apply(a: number, b: number, c: number): void;
export function __wbg_tictactoegame_free(a: number): void;
export function __wbg_tictactoecommand_free(a: number): void;
export function __wbg_get_tictactoecommand_i(a: number): number;
export function __wbg_set_tictactoecommand_i(a: number, b: number): void;
export function __wbg_get_tictactoecommand_j(a: number): number;
export function __wbg_set_tictactoecommand_j(a: number, b: number): void;
export function tictactoegame_new(): number;
export function tictactoegame_reset(a: number): void;
export function tictactoegame_size(a: number): number;
export function tictactoegame_cell(a: number, b: number, c: number, d: number): void;
export function tictactoegame_player(a: number, b: number): void;
export function tictactoegame_result(a: number, b: number): void;
export function tictactoegame_suggest_move(a: number, b: number): number;
export function tictactoegame_apply(a: number, b: number, c: number, d: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
